/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.rd.chat.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import it.eng.rd.chat.model.ChatConfigure;
import it.eng.rd.chat.service.ChatConfigureService;
import it.eng.rd.chat.service.ChatConfigureServiceUtil;
import it.eng.rd.chat.service.persistence.ChatConfigurePersistence;
import it.eng.rd.chat.service.persistence.ChatMessageFinder;
import it.eng.rd.chat.service.persistence.ChatMessagePersistence;
import it.eng.rd.chat.service.persistence.ChatRequestPersistence;

import java.lang.reflect.Field;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the chat configure remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link it.eng.rd.chat.service.impl.ChatConfigureServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see it.eng.rd.chat.service.impl.ChatConfigureServiceImpl
 * @generated
 */
public abstract class ChatConfigureServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, ChatConfigureService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>ChatConfigureService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>ChatConfigureServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
		_setServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			ChatConfigureService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		chatConfigureService = (ChatConfigureService)aopProxy;

		_setServiceUtilService(chatConfigureService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ChatConfigureService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ChatConfigure.class;
	}

	protected String getModelClassName() {
		return ChatConfigure.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = chatConfigurePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setServiceUtilService(
		ChatConfigureService chatConfigureService) {

		try {
			Field field = ChatConfigureServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, chatConfigureService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected it.eng.rd.chat.service.ChatConfigureLocalService
		chatConfigureLocalService;

	protected ChatConfigureService chatConfigureService;

	@Reference
	protected ChatConfigurePersistence chatConfigurePersistence;

	@Reference
	protected ChatMessagePersistence chatMessagePersistence;

	@Reference
	protected ChatMessageFinder chatMessageFinder;

	@Reference
	protected ChatRequestPersistence chatRequestPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

}