/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.rd.collaborativecreation.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Cocreation service. Represents a row in the &quot;COCREATION_Cocreation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.eng.rd.collaborativecreation.model.impl.CocreationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.eng.rd.collaborativecreation.model.impl.CocreationImpl</code>.
 * </p>
 *
 * @author ENGRD
 * @see Cocreation
 * @generated
 */
@ProviderType
public interface CocreationModel
	extends BaseModel<Cocreation>, GroupedModel, MVCCModel, ShardedModel,
			StagedAuditedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cocreation model instance should use the {@link Cocreation} interface instead.
	 */

	/**
	 * Returns the primary key of this cocreation.
	 *
	 * @return the primary key of this cocreation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cocreation.
	 *
	 * @param primaryKey the primary key of this cocreation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this cocreation.
	 *
	 * @return the mvcc version of this cocreation
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this cocreation.
	 *
	 * @param mvccVersion the mvcc version of this cocreation
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this cocreation.
	 *
	 * @return the uuid of this cocreation
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this cocreation.
	 *
	 * @param uuid the uuid of this cocreation
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the cocreation ID of this cocreation.
	 *
	 * @return the cocreation ID of this cocreation
	 */
	public long getCocreationId();

	/**
	 * Sets the cocreation ID of this cocreation.
	 *
	 * @param cocreationId the cocreation ID of this cocreation
	 */
	public void setCocreationId(long cocreationId);

	/**
	 * Returns the challenge ID of this cocreation.
	 *
	 * @return the challenge ID of this cocreation
	 */
	public long getChallengeId();

	/**
	 * Sets the challenge ID of this cocreation.
	 *
	 * @param challengeId the challenge ID of this cocreation
	 */
	public void setChallengeId(long challengeId);

	/**
	 * Returns the group ID of this cocreation.
	 *
	 * @return the group ID of this cocreation
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this cocreation.
	 *
	 * @param groupId the group ID of this cocreation
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this cocreation.
	 *
	 * @return the company ID of this cocreation
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this cocreation.
	 *
	 * @param companyId the company ID of this cocreation
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this cocreation.
	 *
	 * @return the user ID of this cocreation
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this cocreation.
	 *
	 * @param userId the user ID of this cocreation
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this cocreation.
	 *
	 * @return the user uuid of this cocreation
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this cocreation.
	 *
	 * @param userUuid the user uuid of this cocreation
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this cocreation.
	 *
	 * @return the user name of this cocreation
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this cocreation.
	 *
	 * @param userName the user name of this cocreation
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this cocreation.
	 *
	 * @return the create date of this cocreation
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this cocreation.
	 *
	 * @param createDate the create date of this cocreation
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this cocreation.
	 *
	 * @return the modified date of this cocreation
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this cocreation.
	 *
	 * @param modifiedDate the modified date of this cocreation
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this cocreation.
	 *
	 * @return the title of this cocreation
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this cocreation.
	 *
	 * @param title the title of this cocreation
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this cocreation.
	 *
	 * @return the description of this cocreation
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this cocreation.
	 *
	 * @param description the description of this cocreation
	 */
	public void setDescription(String description);

	/**
	 * Returns the dl folder name of this cocreation.
	 *
	 * @return the dl folder name of this cocreation
	 */
	@AutoEscape
	public String getDlFolderName();

	/**
	 * Sets the dl folder name of this cocreation.
	 *
	 * @param dlFolderName the dl folder name of this cocreation
	 */
	public void setDlFolderName(String dlFolderName);

	/**
	 * Returns the ld folder ID of this cocreation.
	 *
	 * @return the ld folder ID of this cocreation
	 */
	public long getLdFolderId();

	/**
	 * Sets the ld folder ID of this cocreation.
	 *
	 * @param ldFolderId the ld folder ID of this cocreation
	 */
	public void setLdFolderId(long ldFolderId);

	/**
	 * Returns the status of this cocreation.
	 *
	 * @return the status of this cocreation
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this cocreation.
	 *
	 * @param status the status of this cocreation
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this cocreation.
	 *
	 * @return the status by user ID of this cocreation
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this cocreation.
	 *
	 * @param statusByUserId the status by user ID of this cocreation
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this cocreation.
	 *
	 * @return the status by user uuid of this cocreation
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this cocreation.
	 *
	 * @param statusByUserUuid the status by user uuid of this cocreation
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this cocreation.
	 *
	 * @return the status by user name of this cocreation
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this cocreation.
	 *
	 * @param statusByUserName the status by user name of this cocreation
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this cocreation.
	 *
	 * @return the status date of this cocreation
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this cocreation.
	 *
	 * @param statusDate the status date of this cocreation
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns <code>true</code> if this cocreation is approved.
	 *
	 * @return <code>true</code> if this cocreation is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this cocreation is denied.
	 *
	 * @return <code>true</code> if this cocreation is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this cocreation is a draft.
	 *
	 * @return <code>true</code> if this cocreation is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this cocreation is expired.
	 *
	 * @return <code>true</code> if this cocreation is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this cocreation is inactive.
	 *
	 * @return <code>true</code> if this cocreation is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this cocreation is incomplete.
	 *
	 * @return <code>true</code> if this cocreation is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this cocreation is pending.
	 *
	 * @return <code>true</code> if this cocreation is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this cocreation is scheduled.
	 *
	 * @return <code>true</code> if this cocreation is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}