/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.rd.collaborativecreation.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Location service. Represents a row in the &quot;COCREATION_Location&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.eng.rd.collaborativecreation.model.impl.LocationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.eng.rd.collaborativecreation.model.impl.LocationImpl</code>.
 * </p>
 *
 * @author ENGRD
 * @see Location
 * @generated
 */
@ProviderType
public interface LocationModel extends BaseModel<Location>, MVCCModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a location model instance should use the {@link Location} interface instead.
	 */

	/**
	 * Returns the primary key of this location.
	 *
	 * @return the primary key of this location
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this location.
	 *
	 * @param primaryKey the primary key of this location
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this location.
	 *
	 * @return the mvcc version of this location
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this location.
	 *
	 * @param mvccVersion the mvcc version of this location
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the location ID of this location.
	 *
	 * @return the location ID of this location
	 */
	public long getLocationId();

	/**
	 * Sets the location ID of this location.
	 *
	 * @param locationId the location ID of this location
	 */
	public void setLocationId(long locationId);

	/**
	 * Returns the challenge ID of this location.
	 *
	 * @return the challenge ID of this location
	 */
	public long getChallengeId();

	/**
	 * Sets the challenge ID of this location.
	 *
	 * @param challengeId the challenge ID of this location
	 */
	public void setChallengeId(long challengeId);

	/**
	 * Returns the name of this location.
	 *
	 * @return the name of this location
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this location.
	 *
	 * @param name the name of this location
	 */
	public void setName(String name);

	/**
	 * Returns the latitude of this location.
	 *
	 * @return the latitude of this location
	 */
	@AutoEscape
	public String getLatitude();

	/**
	 * Sets the latitude of this location.
	 *
	 * @param latitude the latitude of this location
	 */
	public void setLatitude(String latitude);

	/**
	 * Returns the longitude of this location.
	 *
	 * @return the longitude of this location
	 */
	@AutoEscape
	public String getLongitude();

	/**
	 * Sets the longitude of this location.
	 *
	 * @param longitude the longitude of this location
	 */
	public void setLongitude(String longitude);

}