/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.rd.sandbox.request.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Sandbox service. Represents a row in the &quot;sandbox_Sandbox&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.eng.rd.sandbox.request.model.impl.SandboxModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.eng.rd.sandbox.request.model.impl.SandboxImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Sandbox
 * @generated
 */
@ProviderType
public interface SandboxModel
	extends BaseModel<Sandbox>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sandbox model instance should use the {@link Sandbox} interface instead.
	 */

	/**
	 * Returns the primary key of this sandbox.
	 *
	 * @return the primary key of this sandbox
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sandbox.
	 *
	 * @param primaryKey the primary key of this sandbox
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this sandbox.
	 *
	 * @return the uuid of this sandbox
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this sandbox.
	 *
	 * @param uuid the uuid of this sandbox
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the sandbox ID of this sandbox.
	 *
	 * @return the sandbox ID of this sandbox
	 */
	public long getSandboxId();

	/**
	 * Sets the sandbox ID of this sandbox.
	 *
	 * @param sandboxId the sandbox ID of this sandbox
	 */
	public void setSandboxId(long sandboxId);

	/**
	 * Returns the group ID of this sandbox.
	 *
	 * @return the group ID of this sandbox
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this sandbox.
	 *
	 * @param groupId the group ID of this sandbox
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this sandbox.
	 *
	 * @return the company ID of this sandbox
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this sandbox.
	 *
	 * @param companyId the company ID of this sandbox
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this sandbox.
	 *
	 * @return the user ID of this sandbox
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this sandbox.
	 *
	 * @param userId the user ID of this sandbox
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this sandbox.
	 *
	 * @return the user uuid of this sandbox
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this sandbox.
	 *
	 * @param userUuid the user uuid of this sandbox
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this sandbox.
	 *
	 * @return the user name of this sandbox
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this sandbox.
	 *
	 * @param userName the user name of this sandbox
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this sandbox.
	 *
	 * @return the create date of this sandbox
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this sandbox.
	 *
	 * @param createDate the create date of this sandbox
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this sandbox.
	 *
	 * @return the modified date of this sandbox
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this sandbox.
	 *
	 * @param modifiedDate the modified date of this sandbox
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}