/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.rd.dymer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DymerEntry service. Represents a row in the &quot;DYM_DymerEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.eng.rd.dymer.model.impl.DymerEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.eng.rd.dymer.model.impl.DymerEntryImpl</code>.
 * </p>
 *
 * @author ENGRD
 * @see DymerEntry
 * @generated
 */
@ProviderType
public interface DymerEntryModel
	extends BaseModel<DymerEntry>, GroupedModel, MVCCModel, ShardedModel,
			StagedAuditedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dymer entry model instance should use the {@link DymerEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this dymer entry.
	 *
	 * @return the primary key of this dymer entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dymer entry.
	 *
	 * @param primaryKey the primary key of this dymer entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this dymer entry.
	 *
	 * @return the mvcc version of this dymer entry
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this dymer entry.
	 *
	 * @param mvccVersion the mvcc version of this dymer entry
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this dymer entry.
	 *
	 * @return the uuid of this dymer entry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this dymer entry.
	 *
	 * @param uuid the uuid of this dymer entry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the entry ID of this dymer entry.
	 *
	 * @return the entry ID of this dymer entry
	 */
	public long getEntryId();

	/**
	 * Sets the entry ID of this dymer entry.
	 *
	 * @param entryId the entry ID of this dymer entry
	 */
	public void setEntryId(long entryId);

	/**
	 * Returns the index of this dymer entry.
	 *
	 * @return the index of this dymer entry
	 */
	@AutoEscape
	public String getIndex();

	/**
	 * Sets the index of this dymer entry.
	 *
	 * @param index the index of this dymer entry
	 */
	public void setIndex(String index);

	/**
	 * Returns the type of this dymer entry.
	 *
	 * @return the type of this dymer entry
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this dymer entry.
	 *
	 * @param type the type of this dymer entry
	 */
	public void setType(String type);

	/**
	 * Returns the ID of this dymer entry.
	 *
	 * @return the ID of this dymer entry
	 */
	@AutoEscape
	public String getId();

	/**
	 * Sets the ID of this dymer entry.
	 *
	 * @param id the ID of this dymer entry
	 */
	public void setId(String id);

	/**
	 * Returns the title of this dymer entry.
	 *
	 * @return the title of this dymer entry
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this dymer entry.
	 *
	 * @param title the title of this dymer entry
	 */
	public void setTitle(String title);

	/**
	 * Returns the ext content of this dymer entry.
	 *
	 * @return the ext content of this dymer entry
	 */
	@AutoEscape
	public String getExtContent();

	/**
	 * Sets the ext content of this dymer entry.
	 *
	 * @param extContent the ext content of this dymer entry
	 */
	public void setExtContent(String extContent);

	/**
	 * Returns the url of this dymer entry.
	 *
	 * @return the url of this dymer entry
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this dymer entry.
	 *
	 * @param url the url of this dymer entry
	 */
	public void setUrl(String url);

	/**
	 * Returns the dymer ID of this dymer entry.
	 *
	 * @return the dymer ID of this dymer entry
	 */
	public long getDymerId();

	/**
	 * Sets the dymer ID of this dymer entry.
	 *
	 * @param dymerId the dymer ID of this dymer entry
	 */
	public void setDymerId(long dymerId);

	/**
	 * Returns the group ID of this dymer entry.
	 *
	 * @return the group ID of this dymer entry
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this dymer entry.
	 *
	 * @param groupId the group ID of this dymer entry
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this dymer entry.
	 *
	 * @return the company ID of this dymer entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this dymer entry.
	 *
	 * @param companyId the company ID of this dymer entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this dymer entry.
	 *
	 * @return the user ID of this dymer entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this dymer entry.
	 *
	 * @param userId the user ID of this dymer entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this dymer entry.
	 *
	 * @return the user uuid of this dymer entry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this dymer entry.
	 *
	 * @param userUuid the user uuid of this dymer entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this dymer entry.
	 *
	 * @return the user name of this dymer entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this dymer entry.
	 *
	 * @param userName the user name of this dymer entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this dymer entry.
	 *
	 * @return the create date of this dymer entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this dymer entry.
	 *
	 * @param createDate the create date of this dymer entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this dymer entry.
	 *
	 * @return the modified date of this dymer entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dymer entry.
	 *
	 * @param modifiedDate the modified date of this dymer entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this dymer entry.
	 *
	 * @return the status of this dymer entry
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this dymer entry.
	 *
	 * @param status the status of this dymer entry
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this dymer entry.
	 *
	 * @return the status by user ID of this dymer entry
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this dymer entry.
	 *
	 * @param statusByUserId the status by user ID of this dymer entry
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this dymer entry.
	 *
	 * @return the status by user uuid of this dymer entry
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this dymer entry.
	 *
	 * @param statusByUserUuid the status by user uuid of this dymer entry
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this dymer entry.
	 *
	 * @return the status by user name of this dymer entry
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this dymer entry.
	 *
	 * @param statusByUserName the status by user name of this dymer entry
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this dymer entry.
	 *
	 * @return the status date of this dymer entry
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this dymer entry.
	 *
	 * @param statusDate the status date of this dymer entry
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns <code>true</code> if this dymer entry is approved.
	 *
	 * @return <code>true</code> if this dymer entry is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this dymer entry is denied.
	 *
	 * @return <code>true</code> if this dymer entry is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this dymer entry is a draft.
	 *
	 * @return <code>true</code> if this dymer entry is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this dymer entry is expired.
	 *
	 * @return <code>true</code> if this dymer entry is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this dymer entry is inactive.
	 *
	 * @return <code>true</code> if this dymer entry is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this dymer entry is incomplete.
	 *
	 * @return <code>true</code> if this dymer entry is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this dymer entry is pending.
	 *
	 * @return <code>true</code> if this dymer entry is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this dymer entry is scheduled.
	 *
	 * @return <code>true</code> if this dymer entry is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}