/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.rd.collaborativecreation.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;

import it.eng.rd.collaborativecreation.model.Hashtag;
import it.eng.rd.collaborativecreation.model.HashtagModel;
import it.eng.rd.collaborativecreation.model.HashtagSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Hashtag service. Represents a row in the &quot;COCREATION_Hashtag&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>HashtagModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link HashtagImpl}.
 * </p>
 *
 * @author ENGRD
 * @see HashtagImpl
 * @generated
 */
@JSON(strict = true)
public class HashtagModelImpl
	extends BaseModelImpl<Hashtag> implements HashtagModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a hashtag model instance should use the <code>Hashtag</code> interface instead.
	 */
	public static final String TABLE_NAME = "COCREATION_Hashtag";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"hashtagId", Types.BIGINT},
		{"challengeId", Types.BIGINT}, {"name", Types.VARCHAR},
		{"assetTagId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("hashtagId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("challengeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("assetTagId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table COCREATION_Hashtag (mvccVersion LONG default 0 not null,hashtagId LONG not null primary key,challengeId LONG,name VARCHAR(75) null,assetTagId LONG)";

	public static final String TABLE_SQL_DROP = "drop table COCREATION_Hashtag";

	public static final String ORDER_BY_JPQL = " ORDER BY hashtag.name DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY COCREATION_Hashtag.name DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static Hashtag toModel(HashtagSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Hashtag model = new HashtagImpl();

		model.setMvccVersion(soapModel.getMvccVersion());
		model.setHashtagId(soapModel.getHashtagId());
		model.setChallengeId(soapModel.getChallengeId());
		model.setName(soapModel.getName());
		model.setAssetTagId(soapModel.getAssetTagId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<Hashtag> toModels(HashtagSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Hashtag> models = new ArrayList<Hashtag>(soapModels.length);

		for (HashtagSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public HashtagModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _hashtagId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setHashtagId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _hashtagId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Hashtag.class;
	}

	@Override
	public String getModelClassName() {
		return Hashtag.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Hashtag, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Hashtag, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Hashtag, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Hashtag)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Hashtag, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Hashtag, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Hashtag)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Hashtag, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Hashtag, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Hashtag>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Hashtag.class.getClassLoader(), Hashtag.class, ModelWrapper.class);

		try {
			Constructor<Hashtag> constructor =
				(Constructor<Hashtag>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Hashtag, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Hashtag, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Hashtag, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Hashtag, Object>>();
		Map<String, BiConsumer<Hashtag, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Hashtag, ?>>();

		attributeGetterFunctions.put("mvccVersion", Hashtag::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion", (BiConsumer<Hashtag, Long>)Hashtag::setMvccVersion);
		attributeGetterFunctions.put("hashtagId", Hashtag::getHashtagId);
		attributeSetterBiConsumers.put(
			"hashtagId", (BiConsumer<Hashtag, Long>)Hashtag::setHashtagId);
		attributeGetterFunctions.put("challengeId", Hashtag::getChallengeId);
		attributeSetterBiConsumers.put(
			"challengeId", (BiConsumer<Hashtag, Long>)Hashtag::setChallengeId);
		attributeGetterFunctions.put("name", Hashtag::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<Hashtag, String>)Hashtag::setName);
		attributeGetterFunctions.put("assetTagId", Hashtag::getAssetTagId);
		attributeSetterBiConsumers.put(
			"assetTagId", (BiConsumer<Hashtag, Long>)Hashtag::setAssetTagId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getHashtagId() {
		return _hashtagId;
	}

	@Override
	public void setHashtagId(long hashtagId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_hashtagId = hashtagId;
	}

	@JSON
	@Override
	public long getChallengeId() {
		return _challengeId;
	}

	@Override
	public void setChallengeId(long challengeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_challengeId = challengeId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalName() {
		return getColumnOriginalValue("name");
	}

	@JSON
	@Override
	public long getAssetTagId() {
		return _assetTagId;
	}

	@Override
	public void setAssetTagId(long assetTagId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_assetTagId = assetTagId;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Hashtag.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Hashtag toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Hashtag>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		HashtagImpl hashtagImpl = new HashtagImpl();

		hashtagImpl.setMvccVersion(getMvccVersion());
		hashtagImpl.setHashtagId(getHashtagId());
		hashtagImpl.setChallengeId(getChallengeId());
		hashtagImpl.setName(getName());
		hashtagImpl.setAssetTagId(getAssetTagId());

		hashtagImpl.resetOriginalValues();

		return hashtagImpl;
	}

	@Override
	public int compareTo(Hashtag hashtag) {
		int value = 0;

		value = getName().compareTo(hashtag.getName());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Hashtag)) {
			return false;
		}

		Hashtag hashtag = (Hashtag)object;

		long primaryKey = hashtag.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Hashtag> toCacheModel() {
		HashtagCacheModel hashtagCacheModel = new HashtagCacheModel();

		hashtagCacheModel.mvccVersion = getMvccVersion();

		hashtagCacheModel.hashtagId = getHashtagId();

		hashtagCacheModel.challengeId = getChallengeId();

		hashtagCacheModel.name = getName();

		String name = hashtagCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			hashtagCacheModel.name = null;
		}

		hashtagCacheModel.assetTagId = getAssetTagId();

		return hashtagCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Hashtag, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Hashtag, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Hashtag, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Hashtag)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Hashtag, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Hashtag, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Hashtag, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Hashtag)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Hashtag>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _mvccVersion;
	private long _hashtagId;
	private long _challengeId;
	private String _name;
	private long _assetTagId;

	public <T> T getColumnValue(String columnName) {
		Function<Hashtag, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Hashtag)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("hashtagId", _hashtagId);
		_columnOriginalValues.put("challengeId", _challengeId);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("assetTagId", _assetTagId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("hashtagId", 2L);

		columnBitmasks.put("challengeId", 4L);

		columnBitmasks.put("name", 8L);

		columnBitmasks.put("assetTagId", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Hashtag _escapedModel;

}